### ISSUE TITLE
Animated: false not working

### ISSUE THREAD

**Issue by jpghelfi** [tapptitude/TTSegmentedControl#10]
I'm using `selectItemAt(index: someNumber, animated: false)` and it´s animating anyway. Thanks!

**Comment by jpghelfi** [comment]
Got it guys! You are hardcoding `true` in the func `touchesEnded` Here is the code.

        if point == nil {
            return
        }
        if isSwitch && allowToChangeThumb {
            let label = labelForPoint(thumbContainerView.center)
            let otherIndex = allItemLabels.index(of: label) == 1 ? 0 : 1
            let secondLabel = allItemLabels[otherIndex]
            point = secondLabel.center
        }
        changeThumbFrameForPoint(updatePoint(point!), animated: true) // HERE!
        didEndTouchWithPoint(point!)
        allowToChangeThumb = false
    }

**Comment by EfraimB** [comment]
Hello jp, thanks a lot for poiting it out but  `touchesEnded(_ touches:with event:)` is not called at all when calling `selectItemAt(index: animated: )`.  Can you provide us a little more information. In scope of what function are you calling `selectItemAt(index: animated: )`?

**Comment by jpghelfi** [comment]
You´re right, but to OS is calling that function every time the touch ends. So, no matter what value `selectItemAt` has, it´ll always be animated. You know what I mean ?.

So, the question is, how not to animate the transition ? thanks!

**Comment by EfraimB** [comment]
Can't really see how are you triggering `touchesEnded(_ touches:with event:)` by calling `selectItemAt(index: animated: )`. Can you submit the scope where you are calling `selectItemAt(index: animated: )`. Thank you!
