### ISSUE TITLE
set image 

### ISSUE THREAD

**Issue by mitulmarsonia** [tapptitude/TTSegmentedControl#12]
Can we set image instead of itemTitles  ?

**Comment by alextud** [comment]
Can you try to wrap an image into a NSAttributedString using NSTextAttachment() ?

**Comment by EfraimB** [comment]
Hello, this a good idea an we'll consider it as a future update. Feel free to fork, add a feature and submit a pull request! As a workaround you can consider alextud's comment.

**Comment by lohenyumnam** [comment]
@alextud 
> Can you try to wrap an image into a NSAttributedString using NSTextAttachment() ?

@EfraimB 
> Hello, this a good idea an we'll consider it as a future update. Feel free to fork, add a feature and submit a pull request! As a workaround you can consider alextud's comment.

```
 let segmentedControl = TTSegmentedControl()
 segmentedControl.itemTitles = ["Name1", "Name2"]
```

here itemTitles takes only array of string .. how can I implement this workaround ??

**Comment by alextud** [comment]
Here is a working example in having both text and icon on a single tile:

`
// ask segmented control to initialize all elements internally
segmentedControl.layoutSubviews()
        
let imageAttachment = NSTextAttachment()
imageAttachment.image = image
imageAttachment.bounds = CGRect(x: 0, y: -5, width: 20, height: 20)
        
let attributes = segmentedControl.attributedDefaultTitles.first?.mutableCopy() as! NSMutableAttributedString
attributes.append(NSAttributedString(attachment: imageAttachment))
        
let selectedAttributes = segmentedControl.attributedSelectedTitles.first?.mutableCopy() as! NSMutableAttributedString
selectedAttributes.append(NSAttributedString(attachment: imageAttachment))
        
segmentedControl.changeAttributedTitle(attributes, selectedTile: selectedAttributes, atIndex: atIndex)
`
