### ISSUE TITLE
Change itemTitle

### ISSUE THREAD

**Issue by fclauss72** [tapptitude/TTSegmentedControl#20]
Hi,
first of all thanks for your TTSegmentedControl, it is very useful.

My question is:
How can i change the itemTitle after having already definite it?
I tried with a simple new definition but it doesn't works.

Thank you

**Comment by theorange7** [comment]
Hey @fclauss72, not sure if you still need help on this but I managed to get the titles to what I wanted but setting the property `.itemTitles` = ["Title 1", "Title 2"]`. 

You can even change the default/selected text font via: 
`.defaultTextFont = UIFont(name: "HelveticaNeue-Light", size: size)!`
`.selectedTextFont = UIFont(name: "HelveticaNeue-Light", size: size)!`

These properties are all marked @IBInspectable open var.. but somehow they don't show up on the interface builder for me.

**Comment by EfraimB** [comment]
Thanx @theorange7.
