### ISSUE TITLE
how can i disable when item on item1 and touch item1 to item2

### ISSUE THREAD

**Issue by NemoChen317** [tapptitude/TTSegmentedControl#21]
as title , thank you

**Comment by EfraimB** [comment]
Hello, can you please explain what you need with more details. I don't think i get it. Thanks!

**Comment by phucnm** [comment]
@EfraimB  I guess that's when the current item is `item1`, tap `item1` again the control will jump to `item2`. I met this issue as well. Expected behavior should be nothing happens.

**Comment by chansencc** [comment]
> @EfraimB I guess that's when the current item is `item1`, tap `item1` again the control will jump to `item2`. I met this issue as well. Expected behavior should be nothing happens.

The issue is here:
`    fileprivate var isSwitch: Bool {
        return attributedDefaultTitles.count == 2
    }`

Perhaps this should be an open property rather than just assuming if there are only two items that it is a switch.

**Comment by EfraimB** [comment]
Ok, fixed in the last version. https://github.com/tapptitude/TTSegmentedControl/commit/e137d5df71a2dab17dbb6a48211e2f968c923375
