### ISSUE TITLE
Unable to fit size when device is iPhone SE

### ISSUE THREAD

**Issue by mink-lparrouy** [tapptitude/TTSegmentedControl#22]
Hello there,

I'm facing an issue when I used your library with an iPhone SE. I used 3 items and the last item is not display well.

I join a screenshot to help you understand my issue.

<img width="306" alt="capture d ecran 2019-01-23 a 11 43 57" src="https://user-images.githubusercontent.com/22906662/51601266-328de100-1f04-11e9-86e4-764acda6e3b8.png">

Thank you.

**Comment by sc0rch** [comment]
Here is the temporary workaround for iOS 10.*:
```
// after control setup
segmentControl.setNeedsLayout()
segmentControl.layoutIfNeeded()
```
