### ISSUE TITLE
Detecting when an item has been selected

### ISSUE THREAD

**Issue by TriDivide** [tapptitude/TTSegmentedControl#25]
Trying to make use of your library, the customisation is good but it is not documented at all on how to make practical use of the segmented control. It worked completely different to the standard segmented control that comes by default. Tried to use the variable didSelectItemWith, but can't get it to work. Any example you could provide would help.

**Comment by EfraimB** [comment]
Hello, can you provide a code snippet on how are you using this method. It's pretty straightforward, just have to provide a value for that callback:

```
segmentedControl.didSelectItemWith = {(index,value) in
    print(index)
}
```

**Comment by TriDivide** [comment]
This worked perfectly. Thank you for the help. Obviously there are still gaps in my knowledge regarding closures.
