### ISSUE TITLE
Update to swift 5.0

### ISSUE THREAD

**Issue by harishchopra86** [tapptitude/TTSegmentedControl#26]
I want to use this awesome library in my project. 
However my project is in swift 5 so are there any plans to convert it to swift 5 anytime soon?

Thanks

**Comment by Mahdimm** [comment]
Hi, swift 5?????

**Comment by alextud** [comment]
Hey, sorry for delay. Project was updated to swift 5.0.

**Comment by Mahdimm** [comment]
thanks ;)
