### ISSUE TITLE
0.4.7 is the only version available

### ISSUE THREAD

**Issue by Quailcreek** [tapptitude/TTSegmentedControl#27]
Hi,
I'm trying to install version 0.4.9 and the only version that gets installed is 0.4.7.
I have this in the podfile. pod 'TTSegmentedControl', '~> 0.4' and it loads version 0.4.7

If I use pod 'TTSegmentedControl', '~> 0.4.9' it says it doesn't exist. 

So I tried loading it manually by dragging the TTSegmentedControl.swift file into a brand new project. When I create a new TTSegmentedControl, as son as I set the custom class I get the failed to render error. I downloaded the TTSegmentedControl-0.4.9.zip file to get the latest TTSegmentedControl.swift file. Am I not understanding something?

**Comment by alextud** [comment]
Thanks @Quailcreek, changes were pushed to pod main trunk. Should work now.
