### ISSUE TITLE
Chnaging the defaultTextColor after control is created

### ISSUE THREAD

**Issue by Quailcreek** [tapptitude/TTSegmentedControl#28]
Hello,
Is there a way to change the defaultTextColor from outside the initial control creation code? Like from a button tap event.

Thank you

**Comment by EfraimB** [comment]
Hello, I added ```open func reconfigure()``` which you might call after changing any config property at any point of the runtime. For example:
```
segmentedControl.defaultTextColor = UIColor.red
segmentedControl.reconfigure()
```
