### ISSUE TITLE
Zero Indexed

### ISSUE THREAD

**Issue by DonBaronFactory** [tapptitude/TTSegmentedControl#3]
Great component, may I suggest though you make the first item in the segment 0 indexed rather than 1. Every first anything in Swift is always 0 and not 1 ...

keep up the good work... cheers

**Comment by markkrenek** [comment]
Yeah, this is really bad. didSelectItemWith() reports a 1-based index, but selectItemAt() uses a 0-based index. This makes the control very hard to use.

**Comment by loicgriffie** [comment]
+1
