### ISSUE TITLE
Calling "self.view.layoutIfNeeded()" breaks control

### ISSUE THREAD

**Issue by TriDivide** [tapptitude/TTSegmentedControl#31]
In the `viewDidLoad()` function of the View Controller, I call `self.view.layoutIfNeeded()`, When I wasn't calling this, the control was working fine but now it completely breaks the control's settings including the titles, drag settings etc, I am running the latest version of the pod file.

**Comment by EfraimB** [comment]
```viewDidLoad()``` is called before computing any layout. There is no need to call ```layoutIfNeeded()`` ` in ```viewDidLoad()```
