### ISSUE TITLE
index out of range on actual device

### ISSUE THREAD

**Issue by mahadshahib** [tapptitude/TTSegmentedControl#34]
hi I configured it on my simulator and it run perfectly but first attempt to run on physical device I get index out of range on the line I commented where Is the problem on this function I see that index variable is -1 I didn't even call this function.

`  
  public func selectItemAt(index: Int, animated: Bool = false) {
        if !isConfigurated {
            currentSelectedIndex = index
            return
        }
        let label = allItemLabels[min(index, attributedDefaultTitles.count)]  //////on this line///////
        selectedLabelsView.isHidden = noItemSelected
        changeThumbFrameForPoint(label.center, animated: animated)
    }
`

**Comment by EfraimB** [comment]
Yep, there is bug there, and it's fixed in the last commit.
