### ISSUE TITLE
How to programmatically change the selection thumb offset?

### ISSUE THREAD

**Issue by kutakmir** [tapptitude/TTSegmentedControl#4]
Is it possible to programmatically change the selection thumb offset depending on e.g. a scroll offset of a associated scrollview? I would like to slide from one segment to another smoothly as I scroll.

**Comment by EfraimB** [comment]
Hello Miroslav, 
You can select the item programmatically by calling ```public func selectItemAt(index: Int, animated: Bool = false)``` though this kind of behavior is not in our scope since we want to keep it consistent with apple's segmented control.
