### ISSUE TITLE
Change Font Type

### ISSUE THREAD

**Issue by milan-mgu** [tapptitude/TTSegmentedControl#41]
Any one can suggest how to change font type in this?

**Comment by id-main** [comment]
use your TTSegmentedControl with **defaultTextFont** and **selectedTextFont** properties, e.g.:
mySegmentedControl.**defaultTextFont** = UIFont.systemFont(ofSize: 18, weight: .medium)
mySegmentedControl.**selectedTextFont** = UIFont.systemFont(ofSize: 18, weight: .medium)
