### ISSUE TITLE
CocoaPods version update

### ISSUE THREAD

**Issue by hamsternik** [tapptitude/TTSegmentedControl#8]
Thanks for your library, it makes development easier :)

But I have a small issue with your library. When I had updated swift version on my main project to 4, I've got 2 errors occurred into Xcode. 
It refers to `NSAttributedStringKey` keys, such as `foregroundColor` and `font`.

I saw in your last commits that you fixed that sometimes ago and also pushed a new version of your library. But despite that, you don't push your up-to-date version into the cocoapods repo.

Please, update your library to give a possibility use up-to-date version just writing `pod 'TTSegmentedControl'`. 

Regards.

**Comment by EfraimB** [comment]
Hello,
Thank you a lot for point this out. Please run the `pod update TTSegmentedControl` in command line then run a `pod install`.
