### ISSUE TITLE
Unable to set the initial index.

### ISSUE THREAD

**Issue by jflow** [tapptitude/TTSegmentedControl#9]
Trying to set an initial selected index via selectItemAt(index: 3). This is not working as expected. When I step through the code and it always states it is not configured. 

I have the controls setup in InterfaceBuilder.

**Comment by EfraimB** [comment]
Hello, can you show me the code where you call selectItemAt(index:) ?

**Comment by jflow** [comment]
self.speedSC?.itemTitles = detail.speed.range
self.speedSC?.defaultTextColor = UIColor.lightGray
self.speedSC?.selectedTextColor = UIColor.black
self.speedSC?.defaultTextFont = UIFont.systemFont(ofSize: 18)
self.speedSC?.selectedTextFont = UIFont.systemFont(ofSize: 24, weight: .bold)
self.speedSC?.allowChangeThumbWidth = false
self.speedSC?.thumbGradientColors = [detail.color, detail.color]
self.speedSC?.layoutSubviews()
self.speedSC?.selectItemAt(index: 3)
self.speedSC?.didSelectItemWith = { (index, title) -> () in
      print("Speed item \(index)")
}

Added the layoutSubViews() as an attempt to get things working. Have also tried selectItemAt(index: 3 , animated: true), and with false.

**Comment by EfraimB** [comment]
Is this in the scope of layoutSubViews() ?

**Comment by Kaakati** [comment]
I managed to set initial selected Item by  using the following:
```swift
let when = DispatchTime.now() + 0.01
DispatchQueue.main.asyncAfter(deadline: when) {
// Your code with delay
self.itemCounters.selectItemAt(index: 1, animated: true)
}
```

**Comment by EfraimB** [comment]
Hello guys! Indeed the `selectItemAt(index:animated:)` was not working properly until the control is configured. It has been fixed now. Thanks a lot for pointing it out and free feel to report any issue.
